---
- name: Configure web server on Rocky 
  hosts: rocky
  become: true 
  tasks:
    - name: Installing nginx 
      dnf: 
        name: nginx  
        state: present
       
       
    - name: Create webroot directory 
      file: 
        path: /webroot/html
        state: directory
        mode: '0755'

    - name: Ensure nginx serves from custom webroot
      lineinfile: 
        path: /etc/nginx/nginx.conf
        regexp: '^\s*root\s+/usr/share/nginx/html;'
        line: '        root /webroot/html;'
      notify: reload nginx

    - name: Deploy custom index demo page
      template:
        src: templates/index.html.j2
        dest: "{{ webroot }}/index.html"
        owner: "{{ web_user }}"
        group: "{{ web_group }}"
        mode: '0644'

    - name: Ensure proper SELinux file context 
      sefcontext: 
        target: "{{ webroot }}(/.*)?"
        setype: "{{  selinux_type }}"
        state: present
      notify: run restorecon

    - name: Installing firewalld 
      dnf: 
        name: firewalld 
        state: present

    - name: Ensure firewalld if running and enabled 
      systemd: 
        name: firewalld 
        state: started
        enabled: true

    - name: Open HTTP port in firewalld 
      firewalld:
        service: "{{ firewall_service }}"
        permanent: true 
        state: enabled 
        immediate: true
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure nginx is running and enabled 
      systemd:
        name: nginx 
        state: started 
        enabled: true 

  handlers: 
    - name: reload nginx
      systemd: 
        name: nginx
        state: reloaded

